id: IC23882AB
ocr_import_info:
  timestamp: '2023-08-17T01:57:40.312390+00:00'
  batch_id: batch-cc67
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-08-17 02:11:43.805537+00:00
last_modified: 2023-08-17 02:11:43.805545+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W23222
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23222
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དགེ་ཚུལ་གྱི་ཚིག་ལེའུར་བྱས་པའི་མཆན་འགྲེལ་ནོར་བུའི་ཕྲེང་བ།
  languages:
  - bo
  author: འཇུ་མི་ཕམ་འཇམ་དབྱངས་རྣམ་རྒྱལ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9967061440208334
  ocr_word_median_confidence_index: 1.0
bases:
  I0858:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0858
      total_pages: 38
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I0858.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9967061440208334
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
